package com.namnguyen.myalarm.util

object Constants {

    const val ACTION_SET_EXACT_ALARM = "ACTION_SET_EXACT_ALARM"
    const val ACTION_SET_REPETITIVE_ALARM = "ACTION_SET_REPETITIVE_ALARM"

    const val EXTRA_EXACT_ALARM_TIME = "EXTRA_EXACT_ALARM_TIME"

    const val CHANNEL_ID = "CHANNEL_ID"
    const val CHANNEL_NAME = "CHANNEL_NAME"
    const val CHANNEL_DESCRIPTION = "THIS IS CHANNEL DESCRIPTION"
}